# ============================================================
# SEALED SECRET: Backend Credentials (ENCRYPTED)
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgB0K+KKlftdicSIzycVsw8SBujZlCVyBuOPQmygDSStlxCc2YyzCa678RvPoXoiyBJq7EnhfRgYoZhAsqAQ7nIby8uyO1uoodv0g6KdX1moOWMTNk8tqX7SqGLLDji6oLEVbQk8YEEiGVYuCEZKA/Zsww/MxIWdBJOHREXWoppxsyzitaeeHhn48wJZ6ypKmGTrabzYkJsS7l5tJp2uSDYwxRlnTpDDQ30ppJR3u3GCC+xpSlDEW4lhGpY8kNWEZx1Vq5Gq947s7jzX2ftu6yRzaVTa9HBZGtboa/4GKX9NwFB8kiFzJ+w1gWZDgiznCjSaHwl1IAU7Ij42A02qyrOrUS6YLXIXpy/56AwSSXtuuN3hgjVXz9sIyYYrX2c2OW43AHd7i5e1iD9uLaiWBXm4aI4DL6IsQ33yKzhKKgG6yt4ZOTBj8pAAdYbFhP6wI3teH3tAntCqdLJhkUFyXh3d8+kmIU6jaoOGkbhQgqLjcKbKTdna/JdIvC8h18PtaCpdPKsWWxYW08dAs9TVxdjNB5YAxA1akBd63KFOmF8uVxBT5CAsBG6WXhIKgRnn83UTuQzrYpdF9xo3MWjWx1nEqxbAyrSvOy0azwjt3X/RBbwMxUGV+fTmi8hcRukSRib85HTUc9s3knPwX3G6m9+cWu7EXbfKpYswdtefEuxrsIUsrCSWpIP/wP1GBX2K8lp3e96CaPs=
    DB_USER: AgAwc3+bK2nPROGlh8j6vg8/heE3b2LjCyaGogROqDFAHP7AzPV2L9qZDGvARj9loemPkxkzCII28+/aNrsfEuQzRwQZkWuZrawRJFPCc7TUiSG/LGbVkfuycG+qSM+A8ZOBgG8YQipgYn8n9Uczk7B9gywYEhLtevm6f7IkMrVD3ZP4o/eyMU0QZy3qyyZWUZr+dSvf7Kqi2NLakZLgUoh9HPRPGc7XVQ81cbokFkBAeu+0/y85ANgXynyLOP2ETk/R2dmsY7Hrs937sjnnSgnomWORNvkcPzZiSWSf2unYfFnEDOpNFSyKgNPOXvqYYAC8UFbALFgiAdvWPUurIG0AD7/J7T5fq6yy8O9bzVJwkWLxMMyW6LJFgO30/2gKMJHt7yjXldzj9EGahAlaycPETAwTgIunQKfO9CM2dyUmqLS46rnlj7W2zH0u8JVZSx7rqkI6+0+3Kzo0ApKpS3/KZOztzRqiiRECwoZ+F7sCYdcAHZ1lRz86FEodKGXjdRGLEf6c8upa6nA1YMN/z5C3UrtvD77r+JcZBQYxCqK+ftyTXrHsEJwQFDxtYwiS9uKeYaUZb81ndPscrqzeDTMv6n6kIcPtEyGXMg0G68bNRIgRE0hPnhbNAlFSDMgdPwOHRNieEki1M8XRbYpK2GTphZShxOMATmQvA4LIwe3c6jxQsQCJOXypNBXTujaBE5pzidcWZCc=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: default
    type: Opaque
