# ============================================================
# SEALED SECRET: Database Password (ENCRYPTED)
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBf5WNnxhXJok9GJAgXdY3LPAl3xHTT3vSY2VY2IxLDeB9X1hlONEJ1R3/XdZ49lTnwebOvjkZHT606806YgJ3hr1FinBX5eP5Bq4PSpU8VJ42I6ZEhvjmQfxXI6hv1Dtr2SA+bUq1osgefCcMa/viFjf51al0TGtg1ccgPWYR4/pZGOHIIXSKUba+uwlxMgYxn2FJkSqats3eL5LekNixLzjpWe5U9cy840ZDZwpEuC9KQdfUG2J6sbvpea8WQBBIO4lQ5uPtLLo/ZSoxBKZzAFxEw5wTGSmPzTDd5bJWIkGE6UR9E/bCK7+gc1TK/oTNguDHRqNDgYW4TEf1wEHCX5tr30HycorTPLg339FJZ+NgoyGD1yf/Og9LCryBf0GyhQCMNZKqI/j216jWO4Nysdm0yIHVEroitzwAI4prD5lNpCUefROpuoT+nXeCV1Mqhs4jruAaLAjxjGtndsS6YlF9khO94mWT7dN2h70xQPB0D+U0bwW6+BsBYrezR9oA5PFGU4dACSgXc43Yb89VZUZTULKxYExIQ4asMwpvETp1WjxHEQKNh1PXJaBhx8kUxckEWS+8ewwlf8eKxE9Y5abhmrrk1Ke+ZRXlHlQEqqOXvNYLnrS0yGKN5eBXMYzBF+55zZ4+p4Fcq2fE4afq7BbloIOyCBC1hOPnVeKSEnzLObFXg27CgBmN7LQjSwnDERGWU8mHE
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secret
      namespace: default
    type: Opaque
