apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Release.Name }}-backend
data:
  DB_HOST: "{{ .Release.Name }}-postgres"
  DB_PORT: "{{ .Values.database.service.port }}"
  DB_NAME: "{{ .Values.database.name }}"
  PORT: "{{ .Values.backend.service.port }}"
