apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | b64enc | quote }}
