apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.auth.username | quote }}
  PGDATA: "/var/lib/postgresql/data/pgdata"
